title: Reiki with Meditation, Market Harborough
url: ""
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: Susanne Trevorrow (c) 2023

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"


